/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import wolfscene from '../Assets/3d/wolf.glb'

const SecondFoxmodel = ({currentAnimation, ...props}) => {
  const group = useRef()
  const { nodes, materials, animations} = useGLTF(wolfscene)
  const wolf = useGLTF(wolfscene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((actions) => actions.stop());

    if(actions[currentAnimation])
        actions[currentAnimation].play();
    
  }, [actions, currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature_0">
          <skinnedMesh
            name="Wolf1_Material__wolf_col_tga_0"
            geometry={nodes.Wolf1_Material__wolf_col_tga_0.geometry}
            material={materials.Wolf_1}
            skeleton={nodes.Wolf1_Material__wolf_col_tga_0.skeleton}
          />
          <skinnedMesh
            name="Wolf2_fur__fella3_jpg_001_0"
            geometry={nodes.Wolf2_fur__fella3_jpg_001_0.geometry}
            material={materials.Wolf_Fur}
            skeleton={nodes.Wolf2_fur__fella3_jpg_001_0.skeleton}
          />
          <skinnedMesh
            name="Wolf3_claws_0"
            geometry={nodes.Wolf3_claws_0.geometry}
            material={materials.Wolf_claws}
            skeleton={nodes.Wolf3_claws_0.skeleton}
          />
          <skinnedMesh
            name="Wolf3_eyes_0"
            geometry={nodes.Wolf3_eyes_0.geometry}
            material={materials['Wolf Eyes']}
            skeleton={nodes.Wolf3_eyes_0.skeleton}
          />
          <skinnedMesh
            name="Wolf3_teeth"
            geometry={nodes.Wolf3_teeth.geometry}
            material={materials['Wolf Teeth']}
            skeleton={nodes.Wolf3_teeth.skeleton}
          />
          <primitive object={nodes._rootJoint} />
        </group>
        {/* <mesh
          name="Circle"
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials['Material.001']}
          position={[0, -0.011, 0]}
          scale={0.637}
        /> */}
        <group name="Sun" position={[0.553, 1.181, 0.892]} rotation={[0.43, -0.322, -0.522]} />
      </group>
    </group>
  )
}

export default SecondFoxmodel
